optimized
Signed-off-by: leleliu008 <leleliu008@gmail.com>

diff --git a/formula/pdfium.yml b/formula/pdfium.yml
--- a/formula/pdfium.yml
+++ b/formula/pdfium.yml
@@ -1,32 +1,39 @@
 pkgtype: lib
 summary: PDF read/write library by Google
 web-url: https://pdfium.googlesource.com/pdfium/
-git-url: https://pdfium.googlesource.com/pdfium
 version: 1
 license: BSD-3-Clause
-dep-upp: git ninja python3
+dep-upp: git gn ninja python3
 
 prepare: |
+    NINJA="$(command -v ninja)" || abort 1 'command not found: ninja'
+       GN="$(command -v gn)"    || abort 1 'command not found: gn'
+
     run cd ..
-    run git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
-    run export PATH="'$PWD/depot_tools:$PATH'"
 
-    run gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
-    run "echo \"target_os = ['android']\" >> .gclient"
-    run "yes | gclient sync"
+    run git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
 
-    run cd pdfium
+    export PATH="$PWD/depot_tools:$PATH"
+    export DEPOT_TOOLS_UPDATE=0
+
+    cat >> .gclient <<EOF
+    solutions = [
+      { "name"        : 'src',
+        "url"         : 'https://pdfium.googlesource.com/pdfium.git',
+        "deps_file"   : 'DEPS',
+        "managed"     : False,
+        "custom_deps" : {},
+        "custom_vars": {},
+      },
+    ]
+    target_os = ['android']
+    EOF
+
+    run gclient sync --verbose
+
+    run cd -
 
     sed_in_place '/PNG_USE_READ_MACROS/a "FPDFSDK_EXPORTS",' BUILD.gn
-
-    GN="$(find "$PWD/buildtools" -name gn)"
-
-    if [ -z "$GN" ] ; then
-        abort 1 "gn command not found."
-    fi
-
-    PACKAGE_INSTALLING_SRC_DIR="$PWD"
-    PACKAGE_BSCRIPT_DIR="$PWD"
 
 install: |
     case $TARGET_PLATFORM_ARCH in
diff --git a/formula/v8.yml b/formula/v8.yml
--- a/formula/v8.yml
+++ b/formula/v8.yml
@@ -1,30 +1,34 @@
 pkgtype: lib
 summary: A high-performance JavaScript and WebAssembly Engine powered by Google
 web-url: https://v8.dev/
-git-url: https://github.com/v8/v8
 version: 9.9.115.8
 license: BSD-3-Clause
-dep-upp: git ninja
+dep-upp: git gn ninja
 
 prepare: |
+    NINJA="$(command -v ninja)" || abort 1 'command not found: ninja'
+       GN="$(command -v gn)"    || abort 1 'command not found: gn'
+
     run cd ..
-    run git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
-    run export PATH="'$PWD/depot_tools:$PATH'"
 
-    run command fetch v8
-    run "echo \"target_os = ['android']\" >> .gclient"
-    run cd v8
-    run git checkout $PACKAGE_VERSION
-    run "yes | gclient sync"
+    run git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
 
-    GN="$(find "$PWD/buildtools" -name gn)"
+    export PATH="$PWD/depot_tools:$PATH"
+    export DEPOT_TOOLS_UPDATE=0
 
-    if [ -z "$GN" ] ; then
-        abort 1 "gn command not found."
-    fi
+    run command fetch --nohistory v8
 
-    PACKAGE_INSTALLING_SRC_DIR="$PWD"
-    PACKAGE_BSCRIPT_DIR="$PWD"
+    cat >> .gclient <<EOF
+    target_os = ['android']
+    EOF
+
+    run git -C v8 checkout "$PACKAGE_VERSION"
+
+    run gclient sync
+
+    run rm -rf   src
+    run ln -s v8 src
+    run mkdir -p src/_
 
 install: |
     case $TARGET_PLATFORM_ARCH in
@@ -34,7 +38,7 @@ install: |
         x86_64)  GN_ARG_TARGET_CPU=x64   ;;
     esac
 
-    run $GN gen . --root="$PACKAGE_BSCRIPT_DIR"
+    run "$GN" gen . --root="$PACKAGE_BSCRIPT_DIR"
 
     cat >> args.gn <<EOF
     is_debug=false
@@ -45,7 +49,7 @@ install: |
     v8_enable_i18n_support=false
     EOF
 
-    run ninja
+    run "$NINJA"
     run install_bins d8
     run install_incs "$PACKAGE_BSCRIPT_DIR"/include/*.h
     run install_libs *.so
diff --git a/formula/webrtc.yml b/formula/webrtc.yml
--- a/formula/webrtc.yml
+++ b/formula/webrtc.yml
@@ -1,10 +1,9 @@
 pkgtype: lib
 summary: Real-Time Communication
 web-url: https://webrtc.org/
-git-url: https://webrtc.googlesource.com/src
 version: 1
 license: BSD-3-Clause
-dep-upp: git ninja
+dep-upp: git gn ninja
 
 # https://webrtc.github.io/webrtc-org/native-code/android/
 prepare: |
@@ -12,18 +11,25 @@ prepare: |
         abort 1 "this library is only supported built on Linux"
     fi
 
+    NINJA="$(command -v ninja)" || abort 1 'command not found: ninja'
+       GN="$(command -v gn)"    || abort 1 'command not found: gn'
+
     run cd ..
-    run git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
-    run export PATH="'$PWD/depot_tools:$PATH'"
 
-    run command fetch --nohooks webrtc_android
-    sed_in_place '/target_os = /d' .gclient
-    run "echo \"target_os = ['android']\" >> .gclient"
-    run cd src
-    run git checkout main
-    run "yes | gclient sync"
+    run git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
 
-    GN="$PACKAGE_BSCRIPT_DIR/buildtools/linux64/gn"
+    export PATH="$PWD/depot_tools:$PATH"
+    export DEPOT_TOOLS_UPDATE=0
+
+    run fetch --nohistory --nohooks webrtc_android
+
+    cat >> .gclient <<EOF
+    target_os = ['android']
+    EOF
+
+    run git -C src checkout main
+
+    run gclient sync --verbose
 
 install: |
     case $TARGET_PLATFORM_ARCH in
@@ -33,7 +39,7 @@ install: |
         x86_64)  GN_ARG_TARGET_CPU=x64   ;;
     esac
 
-    run $GN gen . --root="$PACKAGE_BSCRIPT_DIR"
+    run "$GN" gen . --root="$PACKAGE_BSCRIPT_DIR"
 
     cat >> args.gn <<EOF
     is_debug=false
@@ -42,5 +48,5 @@ install: |
     v8_target_cpu="$GN_ARG_TARGET_CPU"
     EOF
 
-    run ninja
+    run "$NINJA"
     run install_libs *.so
